site_name: Image-ATM
site_author: idealo Data Science Team

nav:
    - Home: index.md
    - Getting Started: start.md
    - Documentation:
        - Client:
            - Client: client/client.md
            - Commands: client/commands.md
            - Config: client/config.md
        - Components:
            - Cloud: components/cloud.md
            - Evaluation: components/evaluation.md
            - Data Preparation: components/data_prep.md
            - Training: components/training.md
        - Handlers:
            - Data Generator: handlers/data_generator.md
            - Image Classifer: handlers/image_classifier.md
            - Images: handlers/images.md
            - Logger: handlers/logger.md
            - Keras Utils: handlers/keras_utils.md
            - Utils: handlers/utils.md
        - Scripts:
            - Run Cloud: scripts/run_cloud.md
            - Run Data Prep: scripts/run_data_prep.md
            - Run Evaluation: scripts/run_evaluation.md
            - Run Training Cloud: scripts/run_training_cloud.md
            - Run Training: scripts/run_training.md
    - Contribution: CONTRIBUTING.md
    - License: LICENSE.md
theme:
  name: 'material'

markdown_extensions:
  - codehilite
